// Root ESLint flat config for packages/core and apps/worker.
// apps/web has its own eslint.config.mjs (generated by create-next-app) that takes precedence.
import tseslint from 'typescript-eslint';

export default tseslint.config(
  { ignores: ['**/dist/', '**/.next/', '**/node_modules/'] },
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
);
